channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - matplotlib=3.4.3
  - numpy=1.21.2
  - cpuonly
  - pytorch=1.9.0
  - scipy=1.7.1
  - pandas # 1.3.4
  - scikit-learn # 1.0.1
  - rpy2 # 3.4.5
  - seaborn # 0.11.2
  - networkx # 2.6.3
  - umap-learn # 0.5.2
  - dionysus # 2.0.8
  - pytorch-lightning # 1.5.5
  - pybind11 #alpeh
  - libboost #aleph
  - pip=21.2.4
  - pip:
    - ipykernel
    - ipywidgets
    - setuptools==57.5.0
    - wheel==0.37.0
    - pymanopt # 2.0.1
    - diode # 1.0.1 -- only needed to execute the notebook CellCycle.ipynb 